# Makefile for alpaca-exporter
# Generated By: Cursor (Claude Sonnet 4.5)

.PHONY: help test test-unit test-integration lint format coverage clean

help:
	@echo "Available targets:"
	@echo "  make test              - Run all tests"
	@echo "  make test-unit         - Run unit tests only"
	@echo "  make test-integration  - Run integration tests only"
	@echo "  make lint              - Run linting"
	@echo "  make format            - Format code"
	@echo "  make coverage          - Run tests with coverage"
	@echo "  make clean             - Clean temporary files"

test:
	python3 -m pytest tests/ -v

test-unit:
	python3 -m pytest tests/unit/ -v

test-integration:
	python3 -m pytest tests/integration/ -v

lint:
	python3 -m ruff check src/ tests/

format:
	python3 -m ruff format src/ tests/

coverage:
	python3 -m pytest tests/ --cov=src --cov-report=html --cov-report=term

clean:
	rm -rf .pytest_cache
	rm -rf htmlcov
	rm -rf .coverage
	rm -rf src/__pycache__
	rm -rf tests/__pycache__
	find . -type d -name __pycache__ -exec rm -rf {} +

