groups:
  - name: device:alerts
    rules:

    - alert: CameraDisconnected
      expr: device:camera:was_connected > 0 AND on(host,device_number)
            device:camera:is_connected == 0 AND on(host)
            device:telescope:is_connected > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        message: Camera "{{ .Labels.Name }}" on host "{{ .Labels.Host }}" has disconnected.

    - alert: DomeDisconnected
      expr: device:dome:was_connected > 0 AND on(host,device_number)
            device:dome:is_connected == 0 AND on(host)
            device:dome:is_open > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        message: Dome "{{ .Labels.Name }}" on host "{{ .Labels.Host }}" has disconnected.

    - alert: FilterWheelDisconnected
      expr: device:filterwheel:was_connected > 0 AND on(host,device_number)
            device:filterwheel:is_connected == 0 AND on(host)
            device:camera:is_connected > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        message: Filter wheel "{{ .Labels.Name }}" on host "{{ .Labels.Host }}" has disconnected.

    - alert: FocuserDisconnected
      expr: device:focuser:was_connected > 0 AND on(host,device_number)
            device:focuser:is_connected == 0 AND on(host)
            device:camera:is_connected > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        message: Focuser "{{ .Labels.Name }}" on host "{{ .Labels.Host }}" has disconnected.

    - alert: ObservingConditionDisconnected
      expr: device:observingcondition:was_connected > 0 AND on(host,device_number)
            device:observingcondition:is_connected == 0 AND on(host)
            device:telescope:is_connected > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        message: Observing condition "{{ .Labels.Name }}" on host "{{ .Labels.Host }}" has disconnected.

    - alert: RotatorDisconnected
      expr: device:rotator:was_connected > 0 AND on(host,device_number)
            device:rotator:is_connected == 0 AND on(host)
            device:camera:is_connected > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        message: Rotator "{{ .Labels.Name }}" on host "{{ .Labels.Host }}" has disconnected.

    - alert: SafetyMonitorDisconnected
      expr: device:safetymonitor:was_connected > 0 AND on(host,device_number)
            device:safetymonitor:is_connected == 0 AND on(host)
            device:telescope:is_connected > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        message: Safety monitor "{{ .Labels.Name }}" on host "{{ .Labels.Host }}" has disconnected.

    - alert: SwitchDisconnected
      expr: device:switch:was_connected > 0 AND on(host,device_number)
            device:switch:is_connected == 0 AND on(host)
            device:telescope:is_connected > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        message: Switch "{{ .Labels.Name }}" on host "{{ .Labels.Host }}" has disconnected.

    - alert: TelescopeDisconnected
      expr: device:telescope:was_connected > 0 AND on(host,device_number)
            device:telescope:is_connected == 0 AND on(host)
            device:camera:is_connected > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        message: Telescope "{{ .Labels.Name }}" on host "{{ .Labels.Host }}" has disconnected.

    - alert: TelescopeMeridianFlipMissed
      expr: device:telescope:meridian_flip_needed>0
      for: 15m
      labels:
        severity: critical
      annotations:
        message: Meridian flip was missed and scope is still tracking.  Stop tracking or force a flip.

    - alert: TelescopeBelowHorizon
      expr: device:telescope:is_tracking * on(instance,device_number) 
            device:telescope:altitude<0
      for: 5m
      labels:
        severity: critical
      annotations:
        message: Telescope is below horizion and tracking.  This is unusual and should be stopped.

    - alert: TelescopeSideOfPierFailure
      expr: device:telescope:is_connected * on() 
            absent(device:telescope:side_of_pier) > 0
      for: 1m
      labels:
        severity: critical
      annotations:
        message: |
          Telescope "{{ .Labels.Name }}" on host "{{ .Labels.Host }}" is not reporting "Side of Pier".
          This indicates failure in the ASCOM driver.
          Reboot the computer and reconnect devices.

    - alert: DeviceConnectionFailure
      expr: alpaca_device_connected == 0
      for: 5m
      labels:
        severity: warning
      annotations:
        message: |
          Unable to connect to {{ .Labels.device_type }}/{{ .Labels.device_number }}.  Verify it is connected.

    - alert: DeviceConnectionFailure
      expr: alpaca_device_connected == 0
      for: 15m
      labels:
        severity: critical
      annotations:
        message: |
          Unable to connect to {{ .Labels.device_type }}/{{ .Labels.device_number }}.  Verify it is connected.

    - alert: CameraDuplicateConfiguration
      expr: count by(name) (alpaca_device_connected * on(host,device_type,device_number) group_right alpaca_camera_ccdtemperature) > 1
      labels:
        severity: critical
      annotations:
        message: |
          More than one camera configured with the same name.  Check ASCOM configuration for each device.  
          Restart metric exporter to clear alert unless device changes are handled gracefully.

    - alert: HighCurrentSpike
      expr: device:switch:is_connected AND on(host,device_number)
            max_over_time(device:switch:Current[30s]) - on(host,device_number,id) avg_over_time(device:switch:Current[1h]) > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        message: There's a sustained spike in current relative to the average draw.

    - alert: VoltageLow
      expr: device:switch:is_connected AND on(host,device_number)
            device:switch:Voltage < 12
      for: 1m
      labels:
        severity: critical
      annotations:
        message: Switch voltage output is low!

    - alert: VoltageHigh
      expr: device:switch:is_connected AND on(host,device_number)
            device:switch:Voltage > 13
      for: 1m
      labels:
        severity: critical
      annotations:
        message: Switch voltage output is high!

    - alert: DeviceDisconnected
      expr: device:status:disconnected>0
      for: 5m
      labels:
        severity: warning
      annotations:
        message: |
          Alpaca metric exporter is unable to connect to {{ .Labels.driver }}.  Verify it is connected.

    - alert: DeviceDisconnected
      expr: device:status:disconnected>0
      for: 15m
      labels:
        severity: critical
      annotations:
        message: |
          Alpaca metric exporter is unable to connect to {{ .Labels.driver }}.  Verify it is connected.

    - alert: DeviceAttributeProblems
      expr: sum without(attribute) (rate(alpaca_error_total[1m]))>0
      for: 1m
      labels:
        severity: warning
      annotations:
        message: |
          Alpaca metric exporter is unable to fetch attributes for device {{ .Labels.device_type }}/{{ .Labels.device_number }} on host '{{ .Labels.host }}'.
          May need to reconnect to device, reboot PC, or completely power down rig.

    - alert: DeviceAttributeProblems
      expr: sum without(attribute) (rate(alpaca_error_total[1m]))>0
      for: 10m
      labels:
        severity: critical
      annotations:
        message: |
          Alpaca metric exporter is unable to fetch attributes for device {{ .Labels.device_type }}/{{ .Labels.device_number }} on host '{{ .Labels.host }}'.
          May need to reconnect to device, reboot PC, or completely power down rig.
