# for more attributes, see https://www.ascom-standards.org/api/#/

# prefix for all camera metric names
metric_prefix: alpaca_camera_

# all exported metrics.
# properties are: alpaca_name, metric_name, at_startup_only
# metric_name defaults to alpaca_name and is always prepended with metric_prefix
# cache_ttl is time for value to be cached in seconds.  default to 0 (no cache).
metrics:
- alpaca_name: cooleron
  metric_name: cooling
- alpaca_name: coolerpower
- alpaca_name: gain
- alpaca_name: lastexposureduration
- alpaca_name: offset
- alpaca_name: setccdtemperature
  metric_name: temperature_setpoint
- alpaca_name: heatsinktemperature
  metric_name: temperature_ambient
