# for more attributes, see https://www.ascom-standards.org/api/#/

# prefix for all focuser metric names
metric_prefix: alpaca_filterwheel_

# all exported metrics.
# properties are: alpaca_name, metric_name, at_startup_only
# metric_name defaults to alpaca_name and is always prepended with metric_prefix
# cache_ttl is time for value to be cached in seconds.  default to 0 (no cache).
metrics:
- alpaca_name: position
