# Generated By: Cursor (Claude Sonnet 4.5)
"""
Application constants and configuration defaults.

This module contains all constant values used throughout the application
to provide a single source of truth for configuration.
"""

# Supported ASCOM Alpaca device types
DEVICE_TYPES = [
    "camera",
    "covercalibrator",
    "dome",
    "filterwheel",
    "focuser",
    "observingconditions",
    "rotator",
    "safetymonitor",
    "switch",
    "telescope",
]

# Default configuration values
DEFAULT_ALPACA_BASE_URL = "http://127.0.0.1:11111/api/v1"
DEFAULT_REFRESH_RATE = 5
DEFAULT_PORT = 9876
